# Generated by Django 5.1.6 on 2025-03-11 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("studios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(
                related_name="chats", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studios.studio"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chats.chat"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="files",
            field=models.ManyToManyField(to="chats.file"),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="chat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="chats.chat"
            ),
        ),
    ]
