# Generated by Django 5.1 on 2025-03-19 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
        ('studios', '0003_studiostatistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.RemoveField(
            model_name='project',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='chat',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chats.project'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Аудио'), ('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chats.message'),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0, help_text='Размер файла в байтах'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='studio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='studio_projects', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='chat_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
