# Generated by Django 5.1 on 2025-03-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_chat_participants_remove_chat_studio_and_more'),
        ('studios', '0003_studiostatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='studios.studio'),
        ),
    ]
