# Generated by Django 5.1 on 2025-03-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projects', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('studio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='studios.studio')),
            ],
        ),
    ]
